![](https://miro.medium.com/max/875/1*cyXCE-JcBelTyrK-58w6_Q.png)

# Introduction

#### Q: What is numpy?
A: A linear algebra library for Python. Almost all of the libraries in the PyData ecosystem rely on numpy as their base, or building blocks. It is actually written in C with bindings to python and is therefore incredibly fast by comparison to coding and optimizing similar functions in python alone. This is why it's a critical package for Data sciences in the python realm. 

#### Q: What are numpy arrays?
A: Numpy arrays are the main way we will use the numpy library in the context of this tutorial. They come in two flavours:
- vectors - strictly 1 dimensional arrays
- matrices - 2 dimensional and beyond. Although note that a matrix may still one row or one column. 


# Numpy Arrays

In [1]:
import numpy as np

The history saving thread hit an unexpected error (DatabaseError('database disk image is malformed')).History will not be written to the database.


### Casting python objects to numpy arrays

In [2]:
# create a standard numpy list 
my_list = [1,2,3,4,5]
print(type(my_list))

<class 'list'>


In [3]:
# cast the list object to a numpy array type
arr = np.array(my_list)
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
# create a list of lists 
mat = [[1,2,3],[4,5,6],[7,8,9]]

# cast to a numpy array, creating a 2d array
arr = np.array(mat)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Using numpy built-in methods for array generation

In [5]:
# similar to python built-in range function.
# also uses similar inclusive/exclusive rules
# for the start, stop values. 
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

The numpy arange function can also take a 3rd parameter which is the step parameter and that dictates how the arange function derives the next value in its sequence. 

In [6]:
# get all even numbers between 0-10
evens = np.arange(0,10,2)
evens

array([0, 2, 4, 6, 8])

In [7]:
# get all the odds between 1,10
odds = np.arange(1,10,2)
odds

array([1, 3, 5, 7, 9])

We can also use othermethods of array generation.

In [14]:
# use numpy to generate an array of zeros.

# single digit creates a vector
arr = np.zeros(5)
print("vector", '\n', type(arr), '\n', arr, '\n')

# create a multi-dimensinal array
# note: the tuple is taken as the form
# of rows, cloumns
arr = np.zeros((5,5))
print("multidimensional", '\n', type(arr), '\n', arr)

vector 
 <class 'numpy.ndarray'> 
 [0. 0. 0. 0. 0.] 

multidimensional 
 <class 'numpy.ndarray'> 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Another possible array generation tool is `linspace`. This allows the programmer to create an evenly distributed amount of elements in an array between the value of `start` and `stop` with a 3rd parameter for number of points between.

In [16]:
arr = np.linspace(5,10, 20)
arr

array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

We can also create a identity matrix which is a linear algebra square matrix with a fox ed diagonal of ones, in a structure of zeros. 

In [17]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.random methods

In [18]:
# note this struct does not require wrapping the 
# values as a tuple. 
np.random.rand(3,5)

array([[0.11981978, 0.86894861, 0.76954324, 0.19842932, 0.96308298],
       [0.51635323, 0.77324231, 0.61682914, 0.04742738, 0.9466581 ],
       [0.81606513, 0.56100625, 0.59874398, 0.63614977, 0.76867576]])

In [20]:
# where we want to wrap around a normal distribution
np.random.randn(5,5)

array([[ 0.55376005, -0.9703    , -0.28753457,  0.81665987,  0.14824513],
       [ 0.1486342 , -0.85716824, -0.50412266, -0.85944944, -0.17401128],
       [-0.81195704, -0.82018481,  0.46985104, -0.52101469, -0.8436827 ],
       [ 0.7520208 ,  0.15908852, -0.83722555, -0.07817761,  0.16397485],
       [ 0.54840988, -0.31715268, -1.02201918,  0.91979636,  0.50754323]])

In [21]:
# random int between a start and stop
# typical inclusive/exclusive ruling
# if only a single parameter is passed it
# is assumed as the stop and an implicit
# zero is taken as a start. 
np.random.randint(20)

8

In [23]:
arr = np.random.randint(1,51, 5)
arr

array([19, 40, 29, 42, 13])