![](https://miro.medium.com/max/875/1*cyXCE-JcBelTyrK-58w6_Q.png)

# Introduction

#### Q: What is numpy?
A: A linear algebra library for Python. Almost all of the libraries in the PyData ecosystem rely on numpy as their base, or building blocks. It is actually written in C with bindings to python and is therefore incredibly fast by comparison to coding and optimizing similar functions in python alone. This is why it's a critical package for Data sciences in the python realm. 

#### Q: What are numpy arrays?
A: Numpy arrays are the main way we will use the numpy library in the context of this tutorial. They come in two flavours:
- vectors - strictly 1 dimensional arrays
- matrices - 2 dimensional and beyond. Although note that a matrix may still one row or one column. 


# Numpy Arrays

In [2]:
import numpy as np

### Casting python objects to numpy arrays

In [4]:
# create a standard numpy list 
my_list = [1,2,3,4,5]
print(type(my_list))

<class 'list'>


In [7]:
# cast the list object to a numpy array type
arr = np.array(my_list)
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
# create a list of lists 
mat = [[1,2,3],[4,5,6],[7,8,9]]

# cast to a numpy array, creating a 2d array
arr = np.array(mat)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Using numpy built-in methods for array generation

In [9]:
# similar to python built-in range function.
# also uses similar inclusive/exclusive rules
# for the start, stop values. 
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

The numpy arange function can also take a 3rd parameter which is the step parameter and that dictates how the arange function derives the next value in its sequence. 

In [10]:
# get all even numbers between 0-10
evens = np.arange(0,10,2)
evens

array([0, 2, 4, 6, 8])

In [11]:
# get all the odds between 1,10
odds = np.arange(1,10,2)
odds

array([1, 3, 5, 7, 9])